### ISSUE TITLE
Spontaneous break of compilation, on a dependency that has been working for months

### ISSUE THREAD

**Issue by max-l** [lumeland/lume#444] opened 2023-07-06 17:17 UTC
### Version

v1.18.1

### Platform

ubuntu

### What steps will reproduce the bug?

Compile a project  with a dependency on https://esm.sh/@tanstack/react-table@8.9.1 

note: react@18.2.0/jsx-dev-runtime also seems to be part of the problem

```

{
  "imports": {
    "lume/": "https://deno.land/x/lume@v1.18.1/",
    "react-table": "https://esm.sh/@tanstack/react-table@8.9.1",
  },
  "scopes": {}
}

```

### How often does it reproduce? Is there a required condition?

reproduces consistently

### What is the expected behavior?

a proper build

### What do you see instead?

```
deno task serve 
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run -A - "-s"
Loading config file file:///home/maxl/dev/altorf/python-lib/openprot_pipeline/site/_config.ts


✘ [ERROR] Expected ";" but found "\x04"

    deno:https://esm.sh/@tanstack/react-table@8.9.1:1:2:
      1 │ !T ��~F5�Z�:W��[�+� �@jmAd��v�ߝ��7��O2��<��T;K�,dl�{�c/e�Z0�Ό@�...
        │   ^
        ╵   ;

✘ [ERROR] Unexpected "�"

    deno:https://esm.sh/v127/react@18.2.0/jsx-dev-runtime:1:1:
      1 │ !� ��:%�E��Z殓�g�<h�!ז`���ŊP��P�VI���X+�g�R�@�d�^ܺ�/��ս"����...
        ╵  ~


```

### Additional information

It has been working until a few minutes ago.

Somehow I thought that having a deno.lock file would bring imunity to "surprize upgrades", seems as if it doesn't.

**Comment by max-l** [comment] 2023-07-06 17:35
I noticed the comment "Ensure cached remote files are refreshed if something fails.
" here:  https://github.com/lumeland/lume/blob/v1.18.1/CHANGELOG.md#fixed


I wonder if this can explain the fact that a dependency problem starts occuring, even though I have not updated any dependencies.

I might be misunderstanding something about the deno.lock file, my understanding is to have a reproducible build, by fixing every dependency (and recursive dependency), to the specific versions.  

It's either not working (likely a deno problem), a problem with esm.sh, or something else.

**Comment by oscarotero** [comment] 2023-07-06 18:24
Do you have a repo that I can try to reproduce this error?

**Comment by max-l** [comment] 2023-07-06 18:32
@oscarotero here's a repo that reproduces it:  https://github.com/max-l/lume-isue-444

**Comment by oscarotero** [comment] 2023-07-06 19:01
It's weird. Looks like esm.sh is returning the code compressed and Deno cannot uncompress?

```js
const path = "https://esm.sh/v127/@tanstack/react-table@8.9.1";
const response = await fetch(path);
const content = await response.text();

console.log({ path, content })

/*
{
  path: "https://esm.sh/v127/@tanstack/react-table@8.9.1",
  content: "!T\x04\x00 ������\x17'0�T����\x13\b\x10+� �@\x02jmAd�\x03�v�ߝ��7��O�a�\x03y\x06\vjiN�����j�\x1e�^�\x18\x13t@'���\x01�,rsJ�\x15�R�=k'F\x17m��:�� Kx�"... 35 more characters
}
*/
```

**Comment by oscarotero** [comment] 2023-07-06 19:23
Okay, It's a bug introduced in Deno version 1.33.2.
It should work in v 1.33.1 so you can use this version until it get fixed.

**Comment by max-l** [comment] 2023-07-06 19:40
Hmm, I downgraded to 1.33.1, and it doesn't fix it: 


```
deno upgrade --version 1.33.1 
Downloading https://github.com/denoland/deno/releases/download/v1.33.1/deno-x86_64-unknown-linux-gnu.zip
Deno is upgrading to version 1.33.1
Archive:  /tmp/.tmp2A6hpr/deno.zip
  inflating: deno                    
Upgraded successfully
Release notes: https://github.com/denoland/deno/releases/tag/v1.33.1
Blog post: https://deno.com/blog/v1.33

deno --version 
deno 1.33.1 (release, x86_64-unknown-linux-gnu)
v8 11.4.183.1
typescript 5.0.3



maxl@maxl-840g8:/tmp/lume-isue-444$ deno task serve 
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run -A - "-s"
Loading config file file:///tmp/lume-isue-444/_config.ts


✘ [ERROR] Unexpected "�"

    deno:https://esm.sh/v127/react@18.2.0:1:1:
      1 │ !� F��_��E0=�`78K(�  �6�� t��SQ�k/�
&�&����ǰ߻��ɓ4ׂW:Ԗ~����*T �-�/���ޯ��~��0=�-}/�>��@Eu�n8q/����פ��n�����3
        ╵  ~
✘ [ERROR] Unexpected "�"
✘ [ERROR] Unexpected "�"
    deno:https://esm.sh/v127/@tanstack/react-table@8.9.1/deno/react-table.mjs:1:0:
    deno:https://esm.sh/v127/d3-scale@4.0.2:1:1:��i{&zEa���u��똟'�FpD@����)PZ1���|�H�g��j����9�#�����W%���*H]�Ζ!�]�14C...
      1 │ !� f��kT�daS�e
                        @~�x�S:�/``�zЎ�y[`m�7�V.Z�O��:&-iTZ�Qdc����$�����y�G�\�ηaz\ZZ�����`�沚��!L�!"����o���g7Uت�}�N�D����*&nc6����...
        ╵  ~expected "�"



```

**Comment by oscarotero** [comment] 2023-07-06 21:01
Ok, I found this: https://github.com/esm-dev/esm.sh/issues/676

So it's a bug in esm.sh

**Comment by ije** [comment] 2023-07-06 23:21
sorry for the breaking deploy! I just fixed, can you please try again? thanks!

**Comment by oscarotero** [comment] 2023-07-07 13:29
Thanks @ije 
I just tried again and it works fine now.
I'm closing this.

**Closed by oscarotero** 2023-07-07 13:29 UTC
Labels: bug
