### ISSUE TITLE
Error: The pages (generated) and (generated) have the same output path "/favicon.ico". Use distinct 'url' values to resolve the conflict

### ISSUE THREAD

**Issue by ooker777** [lumeland/lume#642] opened 2024-08-08 07:32 UTC
Without the favicon plugin, an empty project with only an `index.md` and `favicon.svg` at the root works fine. However, with this config:
```js
import lume from "lume/mod.ts";
import wiki from "wiki/mod.ts";
import favicon from "lume/plugins/favicon.ts";

const site = lume();

site.use(favicon({
  // input: "/favicon.svg",
}));

site.use(wiki());

export default site;
```
The error:
```
deno task build
Task build deno task lume
Task lume echo "import 'lume/cli.ts'" | deno run -A -
Loading config file file:///D:/QC%20supplements/Code/Websites/GW-vat-ly-an-du-trong-triet-hoc/_config.ts
🔥 / <- /index.md
🔥 /styles.css <- /styles.css
🔥 /favicon.ico <- (generated)
🔥 /apple-touch-icon.png <- (generated)       
🔥 /pagefind/pagefind.en_2c8b113be1.pf_meta <-
 (generated)
🔥 /pagefind/wasm.en.pagefind <- (generated)  
🔥 /pagefind/fragment/en_b0352ea.pf_fragment <- (generated)
🔥 /pagefind/index/en_c8c9509.pf_index <- (generated)
🔥 /pagefind/pagefind.js <- (generated)       
🔥 /pagefind/pagefind-highlight.js <- (generated)
🔥 /pagefind/pagefind-ui.js <- (generated)    
🔥 /pagefind/pagefind-ui.css <- (generated)   
🔥 /pagefind/pagefind-modular-ui.js <- (generated)
🔥 /pagefind/pagefind-modular-ui.css <- (generated)
🔥 /pagefind/pagefind-entry.json <- (generated)
Error: The pages (generated) and (generated) have the same output path "/favicon.ico". Use distinct 'url' values to resolve the conflict. 
    at FSWriter.savePage (https://deno.land/x/lume@v2.2.4/core/writer.ts:83:15)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async https://deno.land/x/lume@v2.2.4/core/writer.ts:50:13
    at async Promise.all (index 4)
    at async concurrent (https://deno.land/x/lume@v2.2.4/core/utils/concurrent.ts:21:3)     
    at async FSWriter.savePages (https://deno.land/x/lume@v2.2.4/core/writer.ts:47:5)       
    at async Site.build (https://deno.land/x/lume@v2.2.4/core/site.ts:537:19)
    at async build (https://deno.land/x/lume@v2.2.4/cli/build.ts:22:3)
    at async Command.fn (https://deno.land/x/lume@v2.2.4/cli.ts:147:5)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
```

v2.2.4 on Windows

**Comment by oscarotero** [comment] 2024-08-08 09:06
Favicon plugin is already used by `wiki` theme. If you use it again, it's run twice, generating two favicon.ico files and that's why you get the error, because you're generating the same output file twice.

**Comment by ooker777** [comment] 2024-08-08 10:00
that makes sense. In that case, how can I use a custom path to the favicon? It seems to me that I have to download the theme locally, not importing from the repo

**Comment by oscarotero** [comment] 2024-08-08 11:06
The only way is providing a option in the theme to customize it, but it's not available currently.
Why do you need that?

**Comment by oscarotero** [comment] 2024-08-08 11:37
I just released a new version of the wiki theme and you can customize the favicon plugin:

```js
site.use(wiki({
  favicon: {
    input: "assets/favicon.svg"
  }
}));
```

**Comment by ooker777** [comment] 2024-08-08 13:56
it's still unable to find the favicon. Even when I put it inside the source folder while having the config inside the `assets` one, it still run fine

**Comment by oscarotero** [comment] 2024-08-08 16:00
never mind, I just found the error. It's my fault

**Comment by oscarotero** [comment] 2024-08-08 16:09
fixed in 0.9.2

**Closed by oscarotero** 2024-08-08 16:09 UTC
Labels: bug

**Comment by ooker777** [comment] 2024-12-22 03:46
Can you take a look at this again? This error is thrown with either `site.use(wiki())` or `site.use(wiki({ favicon: { input: "assets/favicon.svg" } }))`:
```
error: Uncaught (in worker "") (in promise) Error: File not found: /favicon.svg
        throw new Error(`File not found: ${options.input}`);
              ^
    at getContent (https://deno.land/x/lume@v2.3.2/plugins/favicon.ts:79:15)
    at eventLoopTick (ext:core/01_core.js:175:7)        
    at async https://deno.land/x/lume@v2.3.2/plugins/favicon.ts:86:23
    at async Events.dispatchEvent (https://deno.land/x/lume@v2.3.2/core/events.ts:46:13)
    at async Site.#buildPages (https://deno.land/x/lume@v2.3.2/core/site.ts:689:7)
    at async Site.build (https://deno.land/x/lume@v2.3.2/core/site.ts:541:9)
    at async buildSite (https://deno.land/x/lume@v2.3.2/cli/utils.ts:48:3)
    at async onmessage (https://deno.land/x/lume@v2.3.2/cli/build_worker.ts:23:16)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:175:7) 
```
lume@v2.4.3, lume_theme_simple_wiki@v0.11.1. The repo: https://github.com/QuaCau-TheSphere/BW-ton-tai-trong-the-gioi-tu-ban

**Comment by oscarotero** [comment] 2024-12-22 18:50
@ooker777 To me it works fine, but you have to do the following:
- Run `deno task lume upgrade` to upgrade Lume and simple wiki theme.
- I see you're overriding the `_includes/layout.vto`. Can I ask why? In any case, the menu doesn't work with your layout. If you remove this file (or update it to [include this script file](https://github.com/lumeland/theme-simple-wiki/blob/main/src/_includes/layout.vto#L12)) it should work fine.

**Comment by ooker777** [comment] 2024-12-23 07:07
1. It seems there is a problem with how Deno deal with modules with unspecified version. (I intentionally do so to get the latest versions.) At first I thought that it's the [caching](https://docs.deno.com/runtime/fundamentals/modules/#reloading-modules "Modules and dependencies") that causes the problem, but using the `--reload` flag doesn't solve. I must specify the version to have it worked. Can you confirm?
2. I just want to add some buttons to other sites, e.g. Discord, YouTube, Facebook, and some more info on the sidebar. It seems that the layout structure has been changed with the new version of the theme

**Comment by oscarotero** [comment] 2024-12-23 09:59
> I intentionally do so to get the latest versions.

Module versions should be always specified. This avoid a lot of problems like different behaviors depending on Deno cache.

The performance issue you have reported on Discord is caused by the menu. In old versions, the menu was generated in the HTML. So a site with 1000 pages had a tree menu of 1000 elements and due the menu is build for all 1000 pages, this means the creation of 1000x1000 = 1 million of new html which make deno-dom library slow.
In recent versions, this have been changed and now, the tree menu is exported to a json, and the menu is generated by the browser with a custom element. This is what have changed in the default layout.

Regarding extra buttons like social media, the new version allows to place links with icons. Take a look to https://vento.js.org/ as an example.
