### ISSUE TITLE
Passing options to plugins

### ISSUE THREAD

**Issue by bryophyta** [lumeland/lume#212] opened 2022-07-10 19:52 UTC
Hi, I was trying to add options to a markdown-it plugin like `markdown-it-toc-done-right`, where [the plugin docs](https://www.npmjs.com/package/markdown-it-toc-done-right#options) suggest passing options as a parameter to the `markdown.use()` call, e.g. 
```js
markdown.use(require("markdown-it-toc-done-right"), options);
```

The [built-in way](https://lume.land/plugins/markdown/#plugins) to add plugins to `markdown-it` in lume doesn't (as far as I can see) give you access to the `markdown` object itself, because the `markdown.use()` calls are done behind the scenes by lume. So I was looking through the source code to see if there was a way to patch lume to allow me to pass options to `markdown-it-toc-done-right`. When I looked, I found that if a markdown plugin is an array, then the contents of the array will be spread into the `markdown.use()` call:
https://github.com/lumeland/lume/blob/c9119b1d1f45b671c603b65178a7c4595aaf4ce4/plugins/markdown.ts#L77-L79

This makes it possible to pass options to a specific markdown-it plugin from lume, by passing an array of the form `[plugin, { options }]` as a value in the `plugins` array in the `markdown` object that's passed to `site.use()`, e.g.:

```js
import lume from "lume/mod.ts";
import toc from "https://ga.jspm.io/npm:markdown-it-toc-done-right@4.2.0/dist/markdownItTocDoneRight.js";

const tocWithOptions = [toc, { level: 2 }];

const markdown = {
  plugins: [anchor, footnote, tocWithOptions],
  keepDefaultPlugins: true,
};

const site = lume({}, { markdown });
```

This does exactly what I was hoping! But I haven't been able to find any mention of this method in the lume docs. So I wanted to ask: Is this the intended behaviour of the lume markdown plugins API? If so, is it documented anywhere?

If it is the intended behaviour, but isn't documented, then I would be happy to open a PR to add it to the docs. If it isn't intended behaviour, would you be open to the idea of making it a stable part of the API? 

Thanks in advance!

**Comment by oscarotero** [comment] 2022-07-10 20:23
Hi.
Yes, it's the intended behavior. In fact, it's used in the lume.land website: https://github.com/lumeland/lume.land/blob/main/_config.ts#L13-L17

And you're right, it's not documented, so a PR is appreciated. Thanks!!

**Comment by bryophyta** [comment] 2022-07-11 10:18
great, thanks very much! I should have thought to check the lume.land code 🤦‍♂️

I'll try to open a docs PR in the next few days

**Comment by bryophyta** [comment] 2022-07-11 17:27
I've opened a PR for this in the docs repo: https://github.com/lumeland/lume.land/pull/12/files

**Comment by oscarotero** [comment] 2022-07-11 21:09
Merged! Thanks!

**Closed by oscarotero** 2022-07-11 21:09 UTC
